create table customers(
	CUST_ID NUMBER(10),
	CUST_NM VARCHAR2(25),
	CUST_AREA VARCHAR2(25),
	CUST_MO NUMBER(10)
);

declare 
	CUST_ID NUMBER(10);
	CUST_NM VARCHAR2(25);
	CUST_AREA VARCHAR2(25);
	CUST_MO NUMBER(10);
begin
	CUST_ID :=&CUST_ID;
	CUST_NM :='&CUST_NM';
	CUST_AREA :='&CUST_AREA';
	CUST_MO := &CUST_MO;
	
	INSERT INTO customers VALUES (CUST_ID,CUST_NM,CUST_AREA,CUST_MO);
end;
/